export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  CONCURRENT_EDIT_CONFLICT = 'CONCURRENT_EDIT_CONFLICT',
  GROUP_TOKEN_INVALID = 'GROUP_TOKEN_INVALID',
  GROUP_BOT_REMOVED = 'GROUP_BOT_REMOVED',
  CONTEST_ALREADY_DRAWN = 'CONTEST_ALREADY_DRAWN',
  CONTEST_INSUFFICIENT_PARTICIPANTS = 'CONTEST_INSUFFICIENT_PARTICIPANTS',
  REQUEST_ERROR = 'REQUEST_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

/** Default HTTP status implied by a code when the throw site doesn't override it. */
export const DEFAULT_STATUS_FOR_CODE: Record<ErrorCode, number> = {
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.CONCURRENT_EDIT_CONFLICT]: 409,
  [ErrorCode.GROUP_TOKEN_INVALID]: 409,
  [ErrorCode.GROUP_BOT_REMOVED]: 409,
  [ErrorCode.CONTEST_ALREADY_DRAWN]: 409,
  [ErrorCode.CONTEST_INSUFFICIENT_PARTICIPANTS]: 400,
  [ErrorCode.REQUEST_ERROR]: 400,
  [ErrorCode.INTERNAL_ERROR]: 500,
};
